title: Gautam Bhutani
logo: /assets/img/logo.png
description: Well-qualified Data Scientist experienced working with vast data sets to break down information, gather relevant points and solve advanced business problems. Skilled in NLP, Machine learning ,predictive modeling, data mining and hypothetical testing. Offering 6 years of experience in improving business operations with more than 3 years of experience in Data Science.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
