title: Gautam Bhutani
logo: /assets/img/logo.png
description: Well-qualified Data Scientist experienced working with vast data sets to break down information, gather relevant points and solve advanced business problems.
theme: jekyll-theme-minimal
